// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Linkedin Push documents
 */
interface LinkedinPushDocumentData {
  /**
   * Title field in *Linkedin Push*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: linkedin_push.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Label field in *Linkedin Push*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: linkedin_push.label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Linkedin Push document from Prismic
 *
 * - **API ID**: `linkedin_push`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LinkedinPushDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LinkedinPushDocumentData>,
    "linkedin_push",
    Lang
  >;

type NavigationDocumentDataSlicesSlice = NavigationItemSlice;

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Slice Zone field in *Navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavigationDocumentDataSlicesSlice>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | ProjectsGridSlice
  | HomeHeroSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ProjectDocumentDataSlicesSlice =
  | ProjectsNavSlice
  | SimpleVideoSlice
  | StickySectionsSlice
  | KeyFiguresSlice
  | RichTextSlice
  | ProjectHeroSlice;

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice> /**
   * Meta Description field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: project.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: project.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

export type AllDocumentTypes =
  | LinkedinPushDocument
  | NavigationDocument
  | PageDocument
  | ProjectDocument;

/**
 * Primary content in *HomeHero → Default → Primary*
 */
export interface HomeHeroSliceDefaultPrimary {
  /**
   * Title field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Current position date field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.default.primary.current_position_date
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  current_position_date: prismic.KeyTextField;

  /**
   * Current position title field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.default.primary.current_position_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  current_position_title: prismic.KeyTextField;

  /**
   * Current position subtitle field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.default.primary.current_position_subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  current_position_subtitle: prismic.KeyTextField;

  /**
   * Past position date field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.default.primary.past_position_date
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  past_position_date: prismic.KeyTextField;

  /**
   * Past position title field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.default.primary.past_position_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  past_position_title: prismic.KeyTextField;

  /**
   * Past position subtitle field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.default.primary.past_position_subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  past_position_subtitle: prismic.KeyTextField;

  /**
   * Linkedin link field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.default.primary.linkedin_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin_link: prismic.LinkField;

  /**
   * Linkedin link label field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.default.primary.linkedin_link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linkedin_link_label: prismic.KeyTextField;

  /**
   * Project link field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.default.primary.project_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project_link: prismic.LinkField;

  /**
   * Project link label field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.default.primary.project_link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  project_link_label: prismic.KeyTextField;
}

/**
 * Default variation for HomeHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeHero*
 */
type HomeHeroSliceVariation = HomeHeroSliceDefault;

/**
 * HomeHero Shared Slice
 *
 * - **API ID**: `home_hero`
 * - **Description**: HomeHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeHeroSlice = prismic.SharedSlice<
  "home_hero",
  HomeHeroSliceVariation
>;

/**
 * Primary content in *KeyFigures → Default → Primary*
 */
export interface KeyFiguresSliceDefaultPrimary {
  /**
   * Title field in *KeyFigures → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: key_figures.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *KeyFigures → Items*
 */
export interface KeyFiguresSliceDefaultItem {
  /**
   * Figure field in *KeyFigures → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: key_figures.items[].figure
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  figure: prismic.KeyTextField;

  /**
   * Figure title field in *KeyFigures → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: key_figures.items[].figure_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  figure_title: prismic.KeyTextField;

  /**
   * Figure Description field in *KeyFigures → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: key_figures.items[].figure_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  figure_description: prismic.RichTextField;

  /**
   * Accent field in *KeyFigures → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: key_figures.items[].accent
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  accent: prismic.BooleanField;
}

/**
 * Default variation for KeyFigures Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type KeyFiguresSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<KeyFiguresSliceDefaultPrimary>,
  Simplify<KeyFiguresSliceDefaultItem>
>;

/**
 * Slice variation for *KeyFigures*
 */
type KeyFiguresSliceVariation = KeyFiguresSliceDefault;

/**
 * KeyFigures Shared Slice
 *
 * - **API ID**: `key_figures`
 * - **Description**: KeyFigures
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type KeyFiguresSlice = prismic.SharedSlice<
  "key_figures",
  KeyFiguresSliceVariation
>;

/**
 * Primary content in *NavigationItem → Default → Primary*
 */
export interface NavigationItemSliceDefaultPrimary {
  /**
   * Name field in *NavigationItem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Link field in *NavigationItem → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Icon field in *NavigationItem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.default.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  icon: prismic.KeyTextField;
}

/**
 * Default variation for NavigationItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationItemSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NavigationItem*
 */
type NavigationItemSliceVariation = NavigationItemSliceDefault;

/**
 * NavigationItem Shared Slice
 *
 * - **API ID**: `navigation_item`
 * - **Description**: NavigationItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItemSlice = prismic.SharedSlice<
  "navigation_item",
  NavigationItemSliceVariation
>;

/**
 * Primary content in *ProjectHero → Default → Primary*
 */
export interface ProjectHeroSliceDefaultPrimary {
  /**
   * Image field in *ProjectHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *ProjectHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ProjectHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for ProjectHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectHero*
 */
type ProjectHeroSliceVariation = ProjectHeroSliceDefault;

/**
 * ProjectHero Shared Slice
 *
 * - **API ID**: `project_hero`
 * - **Description**: ProjectHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectHeroSlice = prismic.SharedSlice<
  "project_hero",
  ProjectHeroSliceVariation
>;

/**
 * Primary content in *ProjectsGrid → Items*
 */
export interface ProjectsGridSliceDefaultItem {
  /**
   * Project link field in *ProjectsGrid → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_grid.items[].project_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project_link: prismic.LinkField;

  /**
   * Project title field in *ProjectsGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_grid.items[].project_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  project_title: prismic.KeyTextField;

  /**
   * Project thumb field in *ProjectsGrid → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_grid.items[].project_thumb
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  project_thumb: prismic.ImageField<never>;

  /**
   * Accent field in *ProjectsGrid → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: projects_grid.items[].accent
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  accent: prismic.BooleanField;
}

/**
 * Default variation for ProjectsGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ProjectsGridSliceDefaultItem>
>;

/**
 * Slice variation for *ProjectsGrid*
 */
type ProjectsGridSliceVariation = ProjectsGridSliceDefault;

/**
 * ProjectsGrid Shared Slice
 *
 * - **API ID**: `projects_grid`
 * - **Description**: ProjectsGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsGridSlice = prismic.SharedSlice<
  "projects_grid",
  ProjectsGridSliceVariation
>;

/**
 * Primary content in *ProjectsNav → Default → Primary*
 */
export interface ProjectsNavSliceDefaultPrimary {
  /**
   * Previous label field in *ProjectsNav → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_nav.default.primary.previous_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  previous_label: prismic.KeyTextField;

  /**
   * Previous Project name field in *ProjectsNav → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_nav.default.primary.previous_project_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  previous_project_name: prismic.KeyTextField;

  /**
   * Previous Project link field in *ProjectsNav → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_nav.default.primary.previous_project_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  previous_project_link: prismic.LinkField;

  /**
   * Next label field in *ProjectsNav → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_nav.default.primary.next_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  next_label: prismic.KeyTextField;

  /**
   * Next Project name field in *ProjectsNav → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_nav.default.primary.next_project_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  next_project_name: prismic.KeyTextField;

  /**
   * Next Project link field in *ProjectsNav → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: projects_nav.default.primary.next_project_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  next_project_link: prismic.LinkField;
}

/**
 * Default variation for ProjectsNav Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsNavSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectsNavSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectsNav*
 */
type ProjectsNavSliceVariation = ProjectsNavSliceDefault;

/**
 * ProjectsNav Shared Slice
 *
 * - **API ID**: `projects_nav`
 * - **Description**: ProjectsNav
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsNavSlice = prismic.SharedSlice<
  "projects_nav",
  ProjectsNavSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *SimpleVideo → Default → Primary*
 */
export interface SimpleVideoSliceDefaultPrimary {
  /**
   * Source field in *SimpleVideo → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_video.default.primary.source
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  source: prismic.LinkToMediaField;
}

/**
 * Default variation for SimpleVideo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SimpleVideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SimpleVideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SimpleVideo*
 */
type SimpleVideoSliceVariation = SimpleVideoSliceDefault;

/**
 * SimpleVideo Shared Slice
 *
 * - **API ID**: `simple_video`
 * - **Description**: SimpleVideo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SimpleVideoSlice = prismic.SharedSlice<
  "simple_video",
  SimpleVideoSliceVariation
>;

/**
 * Primary content in *StickySections → Default → Primary*
 */
export interface StickySectionsSliceDefaultPrimary {
  /**
   * Title field in *StickySections → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sticky_sections.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *StickySections → Items*
 */
export interface StickySectionsSliceDefaultItem {
  /**
   * Title field in *StickySections → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sticky_sections.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *StickySections → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sticky_sections.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *StickySections → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sticky_sections.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Icon svg path field in *StickySections → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sticky_sections.items[].icon_svg_path
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  icon_svg_path: prismic.KeyTextField;
}

/**
 * Default variation for StickySections Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StickySectionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StickySectionsSliceDefaultPrimary>,
  Simplify<StickySectionsSliceDefaultItem>
>;

/**
 * Slice variation for *StickySections*
 */
type StickySectionsSliceVariation = StickySectionsSliceDefault;

/**
 * StickySections Shared Slice
 *
 * - **API ID**: `sticky_sections`
 * - **Description**: StickySections
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StickySectionsSlice = prismic.SharedSlice<
  "sticky_sections",
  StickySectionsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      LinkedinPushDocument,
      LinkedinPushDocumentData,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataSlicesSlice,
      AllDocumentTypes,
      HomeHeroSlice,
      HomeHeroSliceDefaultPrimary,
      HomeHeroSliceVariation,
      HomeHeroSliceDefault,
      KeyFiguresSlice,
      KeyFiguresSliceDefaultPrimary,
      KeyFiguresSliceDefaultItem,
      KeyFiguresSliceVariation,
      KeyFiguresSliceDefault,
      NavigationItemSlice,
      NavigationItemSliceDefaultPrimary,
      NavigationItemSliceVariation,
      NavigationItemSliceDefault,
      ProjectHeroSlice,
      ProjectHeroSliceDefaultPrimary,
      ProjectHeroSliceVariation,
      ProjectHeroSliceDefault,
      ProjectsGridSlice,
      ProjectsGridSliceDefaultItem,
      ProjectsGridSliceVariation,
      ProjectsGridSliceDefault,
      ProjectsNavSlice,
      ProjectsNavSliceDefaultPrimary,
      ProjectsNavSliceVariation,
      ProjectsNavSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SimpleVideoSlice,
      SimpleVideoSliceDefaultPrimary,
      SimpleVideoSliceVariation,
      SimpleVideoSliceDefault,
      StickySectionsSlice,
      StickySectionsSliceDefaultPrimary,
      StickySectionsSliceDefaultItem,
      StickySectionsSliceVariation,
      StickySectionsSliceDefault,
    };
  }
}
